# Generated by Django 4.0.3 on 2022-03-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210320_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Books', 'Books'), ('Mobile Phones', 'Mobile Phones'), ('Clothes', 'Clothes'), ('Laptop', 'Laptop'), ('Shoes', 'Shoes'), ('Electronics', 'Electronics')], max_length=50, null=True),
        ),
    ]
